### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by hadnazzar**
updated readme file with the correct import

### CODE REVIEW

**Comment by anhtuank7c** [comment]
Is it wrong @hadnazzar ?
Did you test it?

**Comment by anhtuank7c** [comment]
https://developers.google.com/maps/documentation/ios-sdk/start
Screen Shot 2019-04-02 at 8 26 59 AM

**Comment by hadnazzar** [comment]
@anhtuank7c  check out the documentation here

https://github.com/react-native-community/react-native-maps/blob/master/docs/installation.md#enabling-google-maps-on-ios

👍

**Comment by anhtuank7c** [comment]
@hadnazzar both of them works bro.

**Comment by hadnazzar** [comment]
when i try with `@` i get an linter error also other imports was used with `#`

**Pull request closed without merging**
